# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bilibili.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BilibiliVideoDownLoad(object):
    def setupUi(self, BilibiliVideoDownLoad):
        BilibiliVideoDownLoad.setObjectName("BilibiliVideoDownLoad")
        BilibiliVideoDownLoad.resize(442, 318)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BilibiliVideoDownLoad.sizePolicy().hasHeightForWidth())
        BilibiliVideoDownLoad.setSizePolicy(sizePolicy)
        BilibiliVideoDownLoad.setMinimumSize(QtCore.QSize(442, 318))
        BilibiliVideoDownLoad.setMaximumSize(QtCore.QSize(442, 318))
        BilibiliVideoDownLoad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(BilibiliVideoDownLoad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 442, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.label = QtWidgets.QLabel(self.MainPage)
        self.label.setGeometry(QtCore.QRect(30, 20, 371, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(29)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./resources/timg.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.MainPage)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 190, 361, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pBDownLoadOne = QtWidgets.QPushButton(self.layoutWidget)
        self.pBDownLoadOne.setStyleSheet("background-color: rgb(44, 163, 205);\n"
"\n"
"")
        self.pBDownLoadOne.setObjectName("pBDownLoadOne")
        self.verticalLayout_2.addWidget(self.pBDownLoadOne)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pBDownLoadMore = QtWidgets.QPushButton(self.layoutWidget)
        self.pBDownLoadMore.setStyleSheet("background-color: rgb(244, 90, 141);")
        self.pBDownLoadMore.setObjectName("pBDownLoadMore")
        self.verticalLayout_2.addWidget(self.pBDownLoadMore)
        self.stackedWidget.addWidget(self.MainPage)
        self.DownLoadOnePage = QtWidgets.QWidget()
        self.DownLoadOnePage.setObjectName("DownLoadOnePage")
        self.lbInputHere = QtWidgets.QLabel(self.DownLoadOnePage)
        self.lbInputHere.setGeometry(QtCore.QRect(20, 20, 141, 17))
        self.lbInputHere.setObjectName("lbInputHere")
        self.lbParserUrl = QtWidgets.QLabel(self.DownLoadOnePage)
        self.lbParserUrl.setGeometry(QtCore.QRect(20, 90, 131, 17))
        self.lbParserUrl.setObjectName("lbParserUrl")
        self.widget = QtWidgets.QWidget(self.DownLoadOnePage)
        self.widget.setGeometry(QtCore.QRect(20, 50, 401, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lEUrlInput = QtWidgets.QLineEdit(self.widget)
        self.lEUrlInput.setObjectName("lEUrlInput")
        self.horizontalLayout.addWidget(self.lEUrlInput)
        self.pBUrlConfirm = QtWidgets.QPushButton(self.widget)
        self.pBUrlConfirm.setObjectName("pBUrlConfirm")
        self.horizontalLayout.addWidget(self.pBUrlConfirm)
        self.widget1 = QtWidgets.QWidget(self.DownLoadOnePage)
        self.widget1.setGeometry(QtCore.QRect(20, 110, 401, 191))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbVideoName = QtWidgets.QLabel(self.widget1)
        self.lbVideoName.setObjectName("lbVideoName")
        self.horizontalLayout_2.addWidget(self.lbVideoName)
        self.lEVideoName = QtWidgets.QLineEdit(self.widget1)
        self.lEVideoName.setObjectName("lEVideoName")
        self.horizontalLayout_2.addWidget(self.lEVideoName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbPath = QtWidgets.QLabel(self.widget1)
        self.lbPath.setObjectName("lbPath")
        self.horizontalLayout_3.addWidget(self.lbPath)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbCurrentPath = QtWidgets.QLabel(self.widget1)
        self.lbCurrentPath.setMinimumSize(QtCore.QSize(240, 0))
        self.lbCurrentPath.setObjectName("lbCurrentPath")
        self.horizontalLayout_3.addWidget(self.lbCurrentPath)
        self.pBModiryPath = QtWidgets.QPushButton(self.widget1)
        self.pBModiryPath.setObjectName("pBModiryPath")
        self.horizontalLayout_3.addWidget(self.pBModiryPath)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbQuality = QtWidgets.QLabel(self.widget1)
        self.lbQuality.setObjectName("lbQuality")
        self.horizontalLayout_4.addWidget(self.lbQuality)
        self.cBQuality = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBQuality.sizePolicy().hasHeightForWidth())
        self.cBQuality.setSizePolicy(sizePolicy)
        self.cBQuality.setMinimumSize(QtCore.QSize(2, 0))
        self.cBQuality.setCurrentText("")
        self.cBQuality.setObjectName("cBQuality")
        self.horizontalLayout_4.addWidget(self.cBQuality)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pBStartToDownLoad = QtWidgets.QPushButton(self.widget1)
        self.pBStartToDownLoad.setObjectName("pBStartToDownLoad")
        self.horizontalLayout_5.addWidget(self.pBStartToDownLoad)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pBReturn = QtWidgets.QPushButton(self.widget1)
        self.pBReturn.setObjectName("pBReturn")
        self.horizontalLayout_5.addWidget(self.pBReturn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.DownLoadOnePage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        BilibiliVideoDownLoad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BilibiliVideoDownLoad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 25))
        self.menubar.setObjectName("menubar")
        BilibiliVideoDownLoad.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BilibiliVideoDownLoad)
        self.statusbar.setObjectName("statusbar")
        BilibiliVideoDownLoad.setStatusBar(self.statusbar)

        self.retranslateUi(BilibiliVideoDownLoad)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BilibiliVideoDownLoad)

    def retranslateUi(self, BilibiliVideoDownLoad):
        _translate = QtCore.QCoreApplication.translate
        BilibiliVideoDownLoad.setWindowTitle(_translate("BilibiliVideoDownLoad", "MainWindow"))
        self.pBDownLoadOne.setText(_translate("BilibiliVideoDownLoad", "下载单个视频"))
        self.pBDownLoadMore.setText(_translate("BilibiliVideoDownLoad", "批量下载"))
        self.lbInputHere.setText(_translate("BilibiliVideoDownLoad", "在此输入视频链接："))
        self.lbParserUrl.setText(_translate("BilibiliVideoDownLoad", "解析链接中..."))
        self.pBUrlConfirm.setText(_translate("BilibiliVideoDownLoad", "确定"))
        self.lbVideoName.setText(_translate("BilibiliVideoDownLoad", "视频名称："))
        self.lbPath.setText(_translate("BilibiliVideoDownLoad", "保存路径："))
        self.lbCurrentPath.setText(_translate("BilibiliVideoDownLoad", "./"))
        self.pBModiryPath.setText(_translate("BilibiliVideoDownLoad", "点击修改"))
        self.lbQuality.setText(_translate("BilibiliVideoDownLoad", "清晰度："))
        self.pBStartToDownLoad.setText(_translate("BilibiliVideoDownLoad", "开始下载"))
        self.pBReturn.setText(_translate("BilibiliVideoDownLoad", "返回"))


